# Generated by Django 5.0.3 on 2024-04-02 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='materia_chamativa',
            new_name='desc_materia_chamativa',
        ),
    ]
