# Generated by Django 5.0.3 on 2024-04-15 01:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_newsletter_profissao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='data_nascimento',
            new_name='data_de_nascimento',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='profissao',
        ),
        migrations.AddField(
            model_name='cliente',
            name='carreira_de_interesse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.infosprofissao', verbose_name='carreira de interesse'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_inscricao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
