# Generated by Django 5.0.3 on 2024-04-16 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_rename_data_nascimento_cliente_data_de_nascimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_de_nascimento',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='NewsEmpreendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_newsletter', models.CharField(max_length=255)),
                ('link_newsletter', models.URLField()),
                ('titulo_materia_chamariz', models.CharField(max_length=255)),
                ('desc_materia_chamativa', models.TextField()),
                ('qtd_inscritos', models.IntegerField()),
                ('profissao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.infosprofissao')),
            ],
        ),
        migrations.CreateModel(
            name='NewsEmpreendedorInscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.cliente')),
                ('news_empreendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.newsempreendedor')),
            ],
        ),
        migrations.CreateModel(
            name='NewsMercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_newsletter', models.CharField(max_length=255)),
                ('link_newsletter', models.URLField()),
                ('titulo_materia_chamariz', models.CharField(max_length=255)),
                ('desc_materia_chamativa', models.TextField()),
                ('qtd_inscritos', models.IntegerField()),
                ('profissao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.infosprofissao')),
            ],
        ),
        migrations.CreateModel(
            name='NewsMercadoIncricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.cliente')),
                ('news_mercado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.newsmercado')),
            ],
        ),
    ]
