# Generated by Django 5.0.3 on 2024-04-16 00:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_cliente_data_de_nascimento_newsempreendedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricaonewsletter',
            name='data_inscricao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='newsempreendedorinscricao',
            name='data_inscricao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='newsmercadoincricao',
            name='data_inscricao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
