# Generated by Django 5.0.3 on 2024-04-16 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_alter_inscricaonewsletter_data_inscricao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='comparacaoSalarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('junior_clt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pleno_clt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('senior_clt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('junior_pj', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pleno_pj', models.DecimalField(decimal_places=2, max_digits=10)),
                ('senior_pj', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profissao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.infosprofissao')),
            ],
        ),
    ]
