# Generated by Django 5.0.3 on 2024-04-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_comparacaosalarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparacaosalarios',
            name='junior_base',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='comparacaosalarios',
            name='pleno_base',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='comparacaosalarios',
            name='senior_base',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='comparacaosalarios',
            name='junior_clt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='comparacaosalarios',
            name='junior_pj',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='comparacaosalarios',
            name='pleno_clt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='comparacaosalarios',
            name='pleno_pj',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='comparacaosalarios',
            name='senior_clt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='comparacaosalarios',
            name='senior_pj',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
