# Generated by Django 5.0.3 on 2024-04-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_comparacaosalarios_junior_base_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagaemprego',
            name='estado',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
